### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by wombatlabs** [LBRYFoundation/pool#11]
I installed the script on a clean Ubuntu 16.04 server and I get the following errors:

For main.sh
```
exception: CDbConnection failed to open the DB connection.
```

On frontend
```
the server responded with a status of 500
```

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Did you follow all the steps prior to installing the script ? Can you give us a step by step of what you did?

**Comment by wombatlabs** [comment]
I followed the steps found in the readme with a fresh Ubuntu 16.04 VPS:

1. Log in to VPS
2. Create new user - `sudo adduser (username)`
3. Add user to sudo group - `sudo adduser (username) sudo`
4. Log in to new user - `sudo su (username)`
```
cd ~/
wget https://raw.githubusercontent.com/lbryio/pool/next/install.sh && chmod +x install.sh && ./install.sh
```
• Follow the instructions on the screen.

And then ran: `./pool-start.sh`

**Comment by tzarebczan** [comment]
Can you check out these posts to see if anything helps? is mysql running? What inputs did you add on the original screen? Can you try again on another VPS and log your inputs? 

https://stackoverflow.com/questions/22815492/cdbconnection-failed-to-open-the-db-connection-yii
https://stackoverflow.com/questions/53416067/cdbconnection-failed-to-open-the-db-connection-yii-after-moving-to-aws
