### ISSUE TITLE
Syntax error, ./install.sh Last line unexpected end of data

### ISSUE THREAD

**Issue by andrasmining** [LBRYFoundation/pool#18]
when I try to run the script, this error comes. Is this github still up to date?

./install.sh: Zeile 859: Dateiende beim Suchen nach »"« erreicht.
./install.sh: Zeile 860: Syntaxfehler: Unerwartetes Dateiende.

**Comment by Coolguy3289** [comment]
Duplicate issue, a PR was made and will be merged to fix this issue.
#16 details some helpful tips

**Comment by andrasmining** [comment]
I still have the issue after merge. Kindly reopen the ticket. The .sh script has a syntax error, tested on clean ubuntu 18.04 server.

**Comment by Coolguy3289** [comment]
Please continue this issue discussion on the following: https://github.com/LBRYFoundation/pool/issues/16
