### ISSUE TITLE
After clean install blocks are rejected.

### ISSUE THREAD

**Issue by satonio** [LBRYFoundation/pool#7]
I followed the installation instructions and the blocks I tried to mine were rejected.

01:40:27: submit 127.0.0.1 (uid 2) 3883, e7230000, 5adfc055, aba76633, 213553696.000/3145728.000
01:40:33: ERROR: rpc_do_call: 127.0.0.1:14390 500
01:40:33: ERROR LIBRARY Coins Invalid mode
01:40:33: *** REJECTED :( LIBRARY Coins block 359452 2 txs
2018-04-25 01:40:33: REJECTED LBC block 359452
01:40:33: submit 127.0.0.1 (uid 2) 3883, 64400100, 5adfc055, 808f2566, 4426715497.000/2359296.000
01:40:42: submit 127.0.0.1 (uid 2) 3883, 8e110200, 5adfc055, 0b45cd32, 36102421.000/1327104.000
01:40:49: LBC 359452 - diff 5256666.366548417 job f2c to 8/8/8 clients, hash 15495432.206/376286835.505 in 0.3 ms
01:41:52: LBC 359452 - diff 5256666.366548417 job f2d to 8/8/8 clients, hash 14983790.697/376286835.505 in 0.2 ms
01:41:54: submit 127.0.0.1 (uid 2) 3885, aa2a0000, 5adfc0bf, 3e0c9900, 120623418.000/3145728.000
01:42:07: ERROR: rpc_do_call: 127.0.0.1:14390 500
01:42:07: ERROR LIBRARY Coins Invalid mode
01:42:07: *** REJECTED :( LIBRARY Coins block 359452 5 txs
2018-04-25 01:42:07: REJECTED LBC block 359452
01:42:07: submit 127.0.0.1 (uid 2) 3885, 1e5e0000, 5adfc0bf, 204e3f87, 11800638851.000/3145728.000
01:42:09: submit 127.0.0.1 (uid 2) 3885, a0790000, 5adfc0bf, 5c39d890, 172825376.000/3145728.000
01:42:13: LBC 359452 - diff 5256666.366548417 job f2e to 8/8/8 clients, hash 15780338.158/376286835.505 in 0.2 ms
01:42:24: submit 127.0.0.1 (uid 2) 3886, 90b20000, 5adfc0d4, 38608d02, 53237235.000/3145728.000
01:43:17: LBC 359452 - diff 5256666.366548417 job f2f to 8/8/8 clients, hash 16237462.609/376286835.505 in 0.3 ms
01:43:23: ERROR: rpc_do_call: 127.0.0.1:14390 500
01:43:23: ERROR LIBRARY Coins Invalid mode
01:43:23: *** REJECTED :( LIBRARY Coins block 359452 6 txs
2018-04-25 01:43:23: REJECTED LBC block 359452

Also I had problems with the stratum server not starting because non-existent fields in the stratum table and i had to manually fix the database.

**Comment by tzarebczan** [comment]
@satonio we cleaned this up on Discord right? Did you miss a step or was it not included in the install docs?

**Comment by satonio** [comment]
It started working when I activated Has submitblock option in Settings on the coin.
Also had to alter the stratum table to add some fields
Also had to change the coin id in the lbrycrd.conf

I don't remember if I did something more than that.

**Comment by tzarebczan** [comment]
@oakey22 do you think you can fix up the instructions to include the above?

**Comment by alyssaoc** [comment]
@tzarebczan Is this still an open issue?

**Comment by tzarebczan** [comment]
I've pinged @oakey22 about it to make sure we aren't missing anything.

**Comment by alyssaoc** [comment]
closing, reopen if needed
